frame = "full"
vsync = true
wsl   = false

[font]
normal      = ["JetBrainsMono Nerd Font"]
bold        = ["JetBrainsMono Nerd Font"]
italic      = ["Victor Mono"]
bold_italic = ["Victor Mono"]
size        = 17
